# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e0593ce9ebbebbd2fd9c9cd4d7a667bc8f5389fdc7ae2ecf45cbe5474870f5056b46b1606486a49066aea589026a1391616de829e24f7ca4b274f8de80f272

test:
  secret_key_base: 18d1e08d327ed956ef695c268a2f07b6a897deea4ac1a945910baf6056299af3d01d9867b82e00f15082bfa9c04b0f7ea796e8274136cfd6c8b2429fd231fd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
